//
//  HomeView.swift
//  ProjectDigio
//
//  Created by Thiago dos Santos Martins on 30/05/24.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the VIP Swift Xcode Templates(https://github.com/Andrei-Popilian/VIP_Design_Xcode_Template)
//  so you can apply clean architecture to your iOS and MacOS projects,
//  see more http://clean-swift.com
//

import UIKit

protocol HomeViewDelegate where Self: UIViewController {
  
  func sendDataBackToParent(_ data: Data)
}

final class HomeView: UIView {
  
  weak var delegate: HomeViewDelegate?
  
  private enum ViewTrait {
    static let leftMargin: CGFloat = 10.0
  }
}
