//
//  HomePresenter.swift
//  ProjectDigio
//
//  Created by Thiago dos Santos Martins on 30/05/24.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the VIP Swift Xcode Templates(https://github.com/Andrei-Popilian/VIP_Design_Xcode_Template)
//  so you can apply clean architecture to your iOS and MacOS projects,
//  see more http://clean-swift.com
//

import Foundation

protocol HomePresentationLogic {
  func presentResponse(_ response: HomeModel.Response)
}

final class HomePresenter {
  private weak var viewController: HomeDisplayLogic?
  
  init(viewController: HomeDisplayLogic?) {
    self.viewController = viewController
  }
}


// MARK: - HomePresentationLogic
extension HomePresenter: HomePresentationLogic {
  
  func presentResponse(_ response: HomeModel.Response) {
    
    switch response {
      
    case .doSomething(let newItem, let isItem):
      presentDoSomething(newItem, isItem)
    }
  }
}


// MARK: - Private Zone
private extension HomePresenter {
  
  func presentDoSomething(_ newItem: Int, _ isItem: Bool) {
    
    //prepare data for display and send it further
    
    viewController?.displayViewModel(.doSomething(viewModelData: NSObject()))
  }
}
